import type { Metadata } from "next";
import { Poppins, Plus_Jakarta_Sans, Instrument_Serif  } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});
const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal', 'italic'],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/satoshi"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${poppins.variable} ${plusJakartaSans.variable} ${instrumentSerif}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
